"""Add messages table for conversation history

Revision ID: db8a923de76e
Revises: 121e13619297
Create Date: 2025-11-12 23:22:35.291149

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db8a923de76e'
down_revision: Union[str, None] = '121e13619297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('api_key_id', sa.Integer(), nullable=True),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('cleared_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_api_key_id'), 'messages', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_messages_created_at'), 'messages', ['created_at'], unique=False)
    op.create_index(op.f('ix_messages_id'), 'messages', ['id'], unique=False)
    op.create_index(op.f('ix_messages_platform'), 'messages', ['platform'], unique=False)
    op.create_index(op.f('ix_messages_team_id'), 'messages', ['team_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    op.drop_constraint('uq_api_keys_team_id', 'api_keys', type_='unique')
    op.drop_constraint('uq_teams_platform_name', 'teams', type_='unique')
    op.create_index(op.f('ix_teams_platform_name'), 'teams', ['platform_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_teams_platform_name'), table_name='teams')
    op.create_unique_constraint('uq_teams_platform_name', 'teams', ['platform_name'])
    op.create_unique_constraint('uq_api_keys_team_id', 'api_keys', ['team_id'])
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_team_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_platform'), table_name='messages')
    op.drop_index(op.f('ix_messages_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_created_at'), table_name='messages')
    op.drop_index(op.f('ix_messages_api_key_id'), table_name='messages')
    op.drop_table('messages')
    # ### end Alembic commands ###
